// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ownerIdentity: __t.identity().primaryKey().name("owner_identity"),
  email: __t.string(),
  displayName: __t.string().name("display_name"),
  avatarUrl: __t.string().name("avatar_url"),
  createdAt: __t.u64().name("created_at"),
});
