// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  SeasonPayload,
} from "./types";

export default {
  boardId: __t.u64(),
  tmdbId: __t.i64(),
  showTitle: __t.string(),
  showOverview: __t.string(),
  showPosterPath: __t.string(),
  firstAirDate: __t.string(),
  get seasons() {
    return __t.array(SeasonPayload);
  },
};
