// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  boardId: __t.u64().name("board_id"),
  tmdbId: __t.i64().name("tmdb_id"),
  tmdbType: __t.string().name("tmdb_type"),
  mediaType: __t.string().name("media_type"),
  title: __t.string(),
  overview: __t.string(),
  posterUrl: __t.string().name("poster_url"),
  airDate: __t.string().name("air_date"),
  chronoOrder: __t.f64().name("chrono_order"),
  parentId: __t.u64().name("parent_id"),
  laneIndex: __t.u32().name("lane_index"),
  canvasX: __t.f64().name("canvas_x"),
  canvasY: __t.f64().name("canvas_y"),
  addedBy: __t.identity().name("added_by"),
  createdAt: __t.u64().name("created_at"),
});
