// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  ownerIdentity: __t.identity(),
  email: __t.string(),
  displayName: __t.string(),
  avatarUrl: __t.string(),
  createdAt: __t.u64(),
});
export type Account = __Infer<typeof Account>;

export const Board = __t.object("Board", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  title: __t.string(),
  description: __t.string(),
  sharingMode: __t.string(),
  orderingMode: __t.string(),
  inviteToken: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Board = __Infer<typeof Board>;

export const EpisodePayload = __t.object("EpisodePayload", {
  episodeNumber: __t.u32(),
  title: __t.string(),
  overview: __t.string(),
  airDate: __t.string(),
});
export type EpisodePayload = __Infer<typeof EpisodePayload>;

export const MediaItem = __t.object("MediaItem", {
  id: __t.u64(),
  boardId: __t.u64(),
  tmdbId: __t.i64(),
  tmdbType: __t.string(),
  mediaType: __t.string(),
  title: __t.string(),
  overview: __t.string(),
  posterUrl: __t.string(),
  airDate: __t.string(),
  chronoOrder: __t.f64(),
  parentId: __t.u64(),
  laneIndex: __t.u32(),
  canvasX: __t.f64(),
  canvasY: __t.f64(),
  addedBy: __t.identity(),
  createdAt: __t.u64(),
});
export type MediaItem = __Infer<typeof MediaItem>;

export const Participant = __t.object("Participant", {
  id: __t.u64(),
  boardId: __t.u64(),
  participantIdentity: __t.identity(),
  displayName: __t.string(),
  joinedAt: __t.u64(),
});
export type Participant = __Infer<typeof Participant>;

export const SeasonPayload = __t.object("SeasonPayload", {
  seasonNumber: __t.u32(),
  title: __t.string(),
  overview: __t.string(),
  posterPath: __t.string(),
  airDate: __t.string(),
  get episodes() {
    return __t.array(EpisodePayload);
  },
});
export type SeasonPayload = __Infer<typeof SeasonPayload>;

export const WatchAggregate = __t.object("WatchAggregate", {
  id: __t.u64(),
  boardId: __t.u64(),
  mediaItemId: __t.u64(),
  watcherIdentity: __t.identity(),
  watchedCount: __t.u32(),
  totalCount: __t.u32(),
  updatedAt: __t.u64(),
});
export type WatchAggregate = __Infer<typeof WatchAggregate>;

export const WatchEntry = __t.object("WatchEntry", {
  id: __t.u64(),
  boardId: __t.u64(),
  mediaItemId: __t.u64(),
  watcherIdentity: __t.identity(),
  watched: __t.bool(),
  watchedAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type WatchEntry = __Infer<typeof WatchEntry>;

