// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

import {
  TypeBuilder as __TypeBuilder,
  t as __t,
} from "spacetimedb";

export default {
  boardId: __t.u64(),
  mediaItemId: __t.u64(),
  newChronoOrder: __t.f64(),
};
