// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  boardId: __t.u64().name("board_id"),
  mediaItemId: __t.u64().name("media_item_id"),
  watcherIdentity: __t.identity().name("watcher_identity"),
  watchedCount: __t.u32().name("watched_count"),
  totalCount: __t.u32().name("total_count"),
  updatedAt: __t.u64().name("updated_at"),
});
