export interface PresetItem {
  tmdbId: number;
  mediaType: 'MOVIE' | 'TV_SHOW';
  title: string;
  chronoOrder: number;
}

export interface Preset {
  id: string;
  name: string;
  description: string;
  icon: string;
  items: PresetItem[];
}

export const PRESETS: Preset[] = [
  {
    id: 'mcu-release',
    name: 'MCU — Release Order',
    description: 'All Marvel Cinematic Universe films & Disney+ shows in release order',
    icon: '🦸',
    items: [
      { tmdbId: 1771, mediaType: 'MOVIE', title: 'Iron Man', chronoOrder: 1 },
      { tmdbId: 10138, mediaType: 'MOVIE', title: 'Iron Man 2', chronoOrder: 2 },
      { tmdbId: 1726, mediaType: 'MOVIE', title: 'The Incredible Hulk', chronoOrder: 3 },
      { tmdbId: 10195, mediaType: 'MOVIE', title: 'Thor', chronoOrder: 4 },
      { tmdbId: 49538, mediaType: 'MOVIE', title: 'Captain America: The First Avenger', chronoOrder: 5 },
      { tmdbId: 24428, mediaType: 'MOVIE', title: 'The Avengers', chronoOrder: 6 },
      { tmdbId: 68721, mediaType: 'MOVIE', title: 'Iron Man 3', chronoOrder: 7 },
      { tmdbId: 76338, mediaType: 'MOVIE', title: 'Thor: The Dark World', chronoOrder: 8 },
      { tmdbId: 100402, mediaType: 'MOVIE', title: 'Captain America: The Winter Soldier', chronoOrder: 9 },
      { tmdbId: 118340, mediaType: 'MOVIE', title: 'Guardians of the Galaxy', chronoOrder: 10 },
      { tmdbId: 99861, mediaType: 'MOVIE', title: 'Avengers: Age of Ultron', chronoOrder: 11 },
      { tmdbId: 102899, mediaType: 'MOVIE', title: 'Ant-Man', chronoOrder: 12 },
      { tmdbId: 271110, mediaType: 'MOVIE', title: 'Captain America: Civil War', chronoOrder: 13 },
      { tmdbId: 283995, mediaType: 'MOVIE', title: 'Guardians of the Galaxy Vol. 2', chronoOrder: 14 },
      { tmdbId: 315635, mediaType: 'MOVIE', title: 'Spider-Man: Homecoming', chronoOrder: 15 },
      { tmdbId: 363088, mediaType: 'MOVIE', title: 'Ant-Man and the Wasp', chronoOrder: 16 },
      { tmdbId: 284052, mediaType: 'MOVIE', title: 'Doctor Strange', chronoOrder: 17 },
      { tmdbId: 284053, mediaType: 'MOVIE', title: 'Thor: Ragnarok', chronoOrder: 18 },
      { tmdbId: 299536, mediaType: 'MOVIE', title: 'Avengers: Infinity War', chronoOrder: 19 },
      { tmdbId: 299534, mediaType: 'MOVIE', title: 'Avengers: Endgame', chronoOrder: 20 },
      { tmdbId: 429617, mediaType: 'MOVIE', title: 'Spider-Man: Far From Home', chronoOrder: 21 },
      { tmdbId: 566525, mediaType: 'MOVIE', title: 'Shang-Chi', chronoOrder: 22 },
      { tmdbId: 616037, mediaType: 'MOVIE', title: 'Thor: Love and Thunder', chronoOrder: 23 },
      { tmdbId: 772515, mediaType: 'MOVIE', title: 'Eternals', chronoOrder: 24 },
      { tmdbId: 634649, mediaType: 'MOVIE', title: 'Spider-Man: No Way Home', chronoOrder: 25 },
      { tmdbId: 848181, mediaType: 'MOVIE', title: 'Black Panther: Wakanda Forever', chronoOrder: 26 },
      { tmdbId: 986056, mediaType: 'MOVIE', title: 'Guardians of the Galaxy Vol. 3', chronoOrder: 27 },
      { tmdbId: 524434, mediaType: 'MOVIE', title: 'The Marvels', chronoOrder: 28 },
      { tmdbId: 829410, mediaType: 'MOVIE', title: 'Deadpool & Wolverine', chronoOrder: 29 },
    ],
  },
  {
    id: 'mcu-chronological',
    name: 'MCU — Chronological',
    description: 'MCU films & shows in in-universe timeline order',
    icon: '⏳',
    items: [
      { tmdbId: 49538, mediaType: 'MOVIE', title: 'Captain America: The First Avenger', chronoOrder: 1 },
      { tmdbId: 1771, mediaType: 'MOVIE', title: 'Iron Man', chronoOrder: 2 },
      { tmdbId: 1726, mediaType: 'MOVIE', title: 'The Incredible Hulk', chronoOrder: 3 },
      { tmdbId: 10138, mediaType: 'MOVIE', title: 'Iron Man 2', chronoOrder: 4 },
      { tmdbId: 10195, mediaType: 'MOVIE', title: 'Thor', chronoOrder: 5 },
      { tmdbId: 24428, mediaType: 'MOVIE', title: 'The Avengers', chronoOrder: 6 },
      { tmdbId: 68721, mediaType: 'MOVIE', title: 'Iron Man 3', chronoOrder: 7 },
      { tmdbId: 76338, mediaType: 'MOVIE', title: 'Thor: The Dark World', chronoOrder: 8 },
      { tmdbId: 100402, mediaType: 'MOVIE', title: 'Captain America: The Winter Soldier', chronoOrder: 9 },
      { tmdbId: 118340, mediaType: 'MOVIE', title: 'Guardians of the Galaxy', chronoOrder: 10 },
      { tmdbId: 283995, mediaType: 'MOVIE', title: 'Guardians of the Galaxy Vol. 2', chronoOrder: 11 },
      { tmdbId: 99861, mediaType: 'MOVIE', title: 'Avengers: Age of Ultron', chronoOrder: 12 },
      { tmdbId: 102899, mediaType: 'MOVIE', title: 'Ant-Man', chronoOrder: 13 },
      { tmdbId: 271110, mediaType: 'MOVIE', title: 'Captain America: Civil War', chronoOrder: 14 },
      { tmdbId: 284052, mediaType: 'MOVIE', title: 'Doctor Strange', chronoOrder: 15 },
      { tmdbId: 315635, mediaType: 'MOVIE', title: 'Spider-Man: Homecoming', chronoOrder: 16 },
      { tmdbId: 284053, mediaType: 'MOVIE', title: 'Thor: Ragnarok', chronoOrder: 17 },
      { tmdbId: 363088, mediaType: 'MOVIE', title: 'Ant-Man and the Wasp', chronoOrder: 18 },
      { tmdbId: 299536, mediaType: 'MOVIE', title: 'Avengers: Infinity War', chronoOrder: 19 },
      { tmdbId: 299534, mediaType: 'MOVIE', title: 'Avengers: Endgame', chronoOrder: 20 },
      { tmdbId: 429617, mediaType: 'MOVIE', title: 'Spider-Man: Far From Home', chronoOrder: 21 },
      { tmdbId: 566525, mediaType: 'MOVIE', title: 'Shang-Chi', chronoOrder: 22 },
      { tmdbId: 772515, mediaType: 'MOVIE', title: 'Eternals', chronoOrder: 23 },
      { tmdbId: 616037, mediaType: 'MOVIE', title: 'Thor: Love and Thunder', chronoOrder: 24 },
      { tmdbId: 634649, mediaType: 'MOVIE', title: 'Spider-Man: No Way Home', chronoOrder: 25 },
      { tmdbId: 848181, mediaType: 'MOVIE', title: 'Black Panther: Wakanda Forever', chronoOrder: 26 },
      { tmdbId: 986056, mediaType: 'MOVIE', title: 'Guardians of the Galaxy Vol. 3', chronoOrder: 27 },
      { tmdbId: 524434, mediaType: 'MOVIE', title: 'The Marvels', chronoOrder: 28 },
      { tmdbId: 829410, mediaType: 'MOVIE', title: 'Deadpool & Wolverine', chronoOrder: 29 },
    ],
  },
  {
    id: 'star-wars-machete',
    name: 'Star Wars — Machete Order',
    description: 'IV, V, I, II, III, VI, VII, VIII, IX — the fan-favorite watch order',
    icon: '⚔️',
    items: [
      { tmdbId: 11, mediaType: 'MOVIE', title: 'Star Wars: A New Hope', chronoOrder: 1 },
      { tmdbId: 1891, mediaType: 'MOVIE', title: 'The Empire Strikes Back', chronoOrder: 2 },
      { tmdbId: 1892, mediaType: 'MOVIE', title: 'Return of the Jedi', chronoOrder: 3 },
      { tmdbId: 1893, mediaType: 'MOVIE', title: 'The Phantom Menace', chronoOrder: 4 },
      { tmdbId: 1894, mediaType: 'MOVIE', title: 'Attack of the Clones', chronoOrder: 5 },
      { tmdbId: 1895, mediaType: 'MOVIE', title: 'Revenge of the Sith', chronoOrder: 6 },
      { tmdbId: 140607, mediaType: 'MOVIE', title: 'The Force Awakens', chronoOrder: 7 },
      { tmdbId: 181808, mediaType: 'MOVIE', title: 'The Last Jedi', chronoOrder: 8 },
      { tmdbId: 181812, mediaType: 'MOVIE', title: 'The Rise of Skywalker', chronoOrder: 9 },
    ],
  },
  {
    id: 'star-wars-full',
    name: 'Star Wars — Full Saga',
    description: 'All Star Wars films in release order including spin-offs',
    icon: '🌌',
    items: [
      { tmdbId: 11, mediaType: 'MOVIE', title: 'Star Wars: A New Hope', chronoOrder: 1 },
      { tmdbId: 1891, mediaType: 'MOVIE', title: 'The Empire Strikes Back', chronoOrder: 2 },
      { tmdbId: 1892, mediaType: 'MOVIE', title: 'Return of the Jedi', chronoOrder: 3 },
      { tmdbId: 1893, mediaType: 'MOVIE', title: 'The Phantom Menace', chronoOrder: 4 },
      { tmdbId: 1894, mediaType: 'MOVIE', title: 'Attack of the Clones', chronoOrder: 5 },
      { tmdbId: 1895, mediaType: 'MOVIE', title: 'Revenge of the Sith', chronoOrder: 6 },
      { tmdbId: 140607, mediaType: 'MOVIE', title: 'The Force Awakens', chronoOrder: 7 },
      { tmdbId: 330459, mediaType: 'MOVIE', title: 'Rogue One', chronoOrder: 8 },
      { tmdbId: 181808, mediaType: 'MOVIE', title: 'The Last Jedi', chronoOrder: 9 },
      { tmdbId: 348350, mediaType: 'MOVIE', title: 'Solo', chronoOrder: 10 },
      { tmdbId: 181812, mediaType: 'MOVIE', title: 'The Rise of Skywalker', chronoOrder: 11 },
    ],
  },
  {
    id: 'lotr',
    name: 'Lord of the Rings',
    description: 'The Hobbit & Lord of the Rings trilogies in chronological order',
    icon: '💍',
    items: [
      { tmdbId: 49051, mediaType: 'MOVIE', title: 'The Hobbit: An Unexpected Journey', chronoOrder: 1 },
      { tmdbId: 57158, mediaType: 'MOVIE', title: 'The Hobbit: The Desolation of Smaug', chronoOrder: 2 },
      { tmdbId: 122917, mediaType: 'MOVIE', title: 'The Hobbit: The Battle of the Five Armies', chronoOrder: 3 },
      { tmdbId: 120, mediaType: 'MOVIE', title: 'The Fellowship of the Ring', chronoOrder: 4 },
      { tmdbId: 121, mediaType: 'MOVIE', title: 'The Two Towers', chronoOrder: 5 },
      { tmdbId: 122, mediaType: 'MOVIE', title: 'The Return of the King', chronoOrder: 6 },
    ],
  },
  {
    id: 'harry-potter',
    name: 'Harry Potter',
    description: 'All 8 Harry Potter films + Fantastic Beasts',
    icon: '⚡',
    items: [
      { tmdbId: 671, mediaType: 'MOVIE', title: "Harry Potter and the Philosopher's Stone", chronoOrder: 1 },
      { tmdbId: 672, mediaType: 'MOVIE', title: 'Harry Potter and the Chamber of Secrets', chronoOrder: 2 },
      { tmdbId: 673, mediaType: 'MOVIE', title: 'Harry Potter and the Prisoner of Azkaban', chronoOrder: 3 },
      { tmdbId: 674, mediaType: 'MOVIE', title: 'Harry Potter and the Goblet of Fire', chronoOrder: 4 },
      { tmdbId: 675, mediaType: 'MOVIE', title: 'Harry Potter and the Order of the Phoenix', chronoOrder: 5 },
      { tmdbId: 767, mediaType: 'MOVIE', title: 'Harry Potter and the Half-Blood Prince', chronoOrder: 6 },
      { tmdbId: 12444, mediaType: 'MOVIE', title: 'Harry Potter and the Deathly Hallows – Part 1', chronoOrder: 7 },
      { tmdbId: 12445, mediaType: 'MOVIE', title: 'Harry Potter and the Deathly Hallows – Part 2', chronoOrder: 8 },
      { tmdbId: 338952, mediaType: 'MOVIE', title: 'Fantastic Beasts and Where to Find Them', chronoOrder: 9 },
      { tmdbId: 338953, mediaType: 'MOVIE', title: 'Fantastic Beasts: The Crimes of Grindelwald', chronoOrder: 10 },
    ],
  },
  {
    id: 'bond',
    name: 'James Bond',
    description: 'All Eon Productions James Bond films in release order',
    icon: '🔫',
    items: [
      { tmdbId: 681, mediaType: 'MOVIE', title: 'Dr. No', chronoOrder: 1 },
      { tmdbId: 682, mediaType: 'MOVIE', title: 'From Russia with Love', chronoOrder: 2 },
      { tmdbId: 683, mediaType: 'MOVIE', title: 'Goldfinger', chronoOrder: 3 },
      { tmdbId: 684, mediaType: 'MOVIE', title: 'Thunderball', chronoOrder: 4 },
      { tmdbId: 685, mediaType: 'MOVIE', title: 'Casino Royale (1967)', chronoOrder: 5 },
      { tmdbId: 686, mediaType: 'MOVIE', title: 'You Only Live Twice', chronoOrder: 6 },
      { tmdbId: 687, mediaType: 'MOVIE', title: "On Her Majesty's Secret Service", chronoOrder: 7 },
      { tmdbId: 688, mediaType: 'MOVIE', title: 'Diamonds Are Forever', chronoOrder: 8 },
      { tmdbId: 689, mediaType: 'MOVIE', title: 'Live and Let Die', chronoOrder: 9 },
      { tmdbId: 690, mediaType: 'MOVIE', title: 'The Man with the Golden Gun', chronoOrder: 10 },
      { tmdbId: 691, mediaType: 'MOVIE', title: 'The Spy Who Loved Me', chronoOrder: 11 },
      { tmdbId: 692, mediaType: 'MOVIE', title: 'Moonraker', chronoOrder: 12 },
      { tmdbId: 693, mediaType: 'MOVIE', title: 'For Your Eyes Only', chronoOrder: 13 },
      { tmdbId: 694, mediaType: 'MOVIE', title: 'Octopussy', chronoOrder: 14 },
      { tmdbId: 695, mediaType: 'MOVIE', title: 'Never Say Never Again', chronoOrder: 15 },
      { tmdbId: 696, mediaType: 'MOVIE', title: 'A View to a Kill', chronoOrder: 16 },
      { tmdbId: 697, mediaType: 'MOVIE', title: 'The Living Daylights', chronoOrder: 17 },
      { tmdbId: 698, mediaType: 'MOVIE', title: 'Licence to Kill', chronoOrder: 18 },
      { tmdbId: 699, mediaType: 'MOVIE', title: 'GoldenEye', chronoOrder: 19 },
      { tmdbId: 700, mediaType: 'MOVIE', title: 'Tomorrow Never Dies', chronoOrder: 20 },
      { tmdbId: 701, mediaType: 'MOVIE', title: 'The World Is Not Enough', chronoOrder: 21 },
      { tmdbId: 702, mediaType: 'MOVIE', title: 'Die Another Day', chronoOrder: 22 },
      { tmdbId: 703, mediaType: 'MOVIE', title: 'Casino Royale', chronoOrder: 23 },
      { tmdbId: 704, mediaType: 'MOVIE', title: 'Quantum of Solace', chronoOrder: 24 },
      { tmdbId: 706, mediaType: 'MOVIE', title: 'Skyfall', chronoOrder: 25 },
      { tmdbId: 707, mediaType: 'MOVIE', title: 'Spectre', chronoOrder: 26 },
      { tmdbId: 370172, mediaType: 'MOVIE', title: 'No Time to Die', chronoOrder: 27 },
    ],
  },
];
