// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateBoardReducer from "../create_board_reducer";
import DeleteBoardReducer from "../delete_board_reducer";
import InsertMovieReducer from "../insert_movie_reducer";
import InsertTvShowReducer from "../insert_tv_show_reducer";
import JoinBoardReducer from "../join_board_reducer";
import RegenerateInviteReducer from "../regenerate_invite_reducer";
import RegisterOwnerReducer from "../register_owner_reducer";
import RemoveMediaItemReducer from "../remove_media_item_reducer";
import RemoveParticipantReducer from "../remove_participant_reducer";
import ResetProgressReducer from "../reset_progress_reducer";
import SetWatchReducer from "../set_watch_reducer";
import SetWatchBulkReducer from "../set_watch_bulk_reducer";
import UpdateBoardReducer from "../update_board_reducer";

export type CreateBoardParams = __Infer<typeof CreateBoardReducer>;
export type DeleteBoardParams = __Infer<typeof DeleteBoardReducer>;
export type InsertMovieParams = __Infer<typeof InsertMovieReducer>;
export type InsertTvShowParams = __Infer<typeof InsertTvShowReducer>;
export type JoinBoardParams = __Infer<typeof JoinBoardReducer>;
export type RegenerateInviteParams = __Infer<typeof RegenerateInviteReducer>;
export type RegisterOwnerParams = __Infer<typeof RegisterOwnerReducer>;
export type RemoveMediaItemParams = __Infer<typeof RemoveMediaItemReducer>;
export type RemoveParticipantParams = __Infer<typeof RemoveParticipantReducer>;
export type ResetProgressParams = __Infer<typeof ResetProgressReducer>;
export type SetWatchParams = __Infer<typeof SetWatchReducer>;
export type SetWatchBulkParams = __Infer<typeof SetWatchBulkReducer>;
export type UpdateBoardParams = __Infer<typeof UpdateBoardReducer>;

